import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/common/header';
import Footer from '@/components/common/footer';
import { ClerkProvider } from '@clerk/nextjs';

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'I built this app Share your Creations',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          footer: 'hidden',
        },
      }}
    >
      <html lang="en">
        <body className={`${outfit.variable} antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

// import { useSignIn } from "@clerk/nextjs";
// export default function CustomSignIn() {
//   const { signIn, setActive } = useSignIn();
//   // your own form here…
//   return (
//     <form>
//       {/* fields for identifier + password */}
//       <button type="submit">Sign In</button>
//       {/* no signup link here */}
//     </form>
//   );
// }
