// All products data - matches schema.ts structure
export const allProducts = [
  {
    id: 1,
    name: 'Modern Full Stack Next.js Course',
    slug: 'modern-full-stack-nextjs-course',
    tagline: 'Learn to build modern full stack applications with Next.js',
    description:
      'Learn to build modern full stack applications with Next.js 16.',
    websiteUrl: 'https://nextjscourse.dev',
    tags: ['Next.js', 'Tailwind CSS', 'Full Stack'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'john@example.com',
    voteCount: 120,
  },
  {
    id: 2,
    name: 'TaskFlow Pro',
    slug: 'taskflow-pro',
    tagline: 'Manage projects like never before',
    description:
      "Streamline your team's workflow with intelligent task management, automated notifications, and real-time collaboration features.",
    websiteUrl: 'https://taskflowpro.example.com',
    tags: ['Productivity', 'SaaS'],
    createdAt: new Date('2024-01-18'),
    approvedAt: new Date('2024-01-19'),
    status: 'approved' as const,
    submittedBy: 'mike@example.com',
    voteCount: 87,
  },
  {
    id: 3,
    name: 'CodeSnap',
    slug: 'codesnap',
    tagline: 'Beautiful code screenshots for developers',
    description:
      'Create stunning code screenshots with customizable themes, syntax highlighting, and export options. Perfect for documentation and social media.',
    websiteUrl: 'https://codesnap.example.com',
    tags: ['Developer Tools', 'Design'],
    createdAt: new Date('2024-01-20'),
    approvedAt: new Date('2024-01-21'),
    status: 'approved' as const,
    submittedBy: 'alex@example.com',
    voteCount: 56,
  },
  {
    id: 4,
    name: 'ProofyBubble',
    slug: 'proofybubble',
    tagline: 'Social proof notifications that convert visitors',
    description:
      'Boost your website conversions with real-time social proof notifications. Show recent purchases, sign-ups, and user activity to build trust and credibility.',
    websiteUrl: 'https://proofybubble.com',
    tags: ['Marketing', 'SaaS', 'Conversion'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'proofy@example.com',
    voteCount: 523,
  },
  {
    id: 5,
    name: 'ParityKit',
    slug: 'paritykit',
    tagline: 'Price parity for global SaaS products',
    description:
      'Maximize your global revenue with intelligent price localization. Automatically adjust pricing based on purchasing power parity to increase conversions worldwide.',
    websiteUrl: 'https://paritykit.com',
    tags: ['SaaS', 'Pricing', 'Global'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'parity@example.com',
    voteCount: 612,
  },
  {
    id: 6,
    name: 'DataViz Pro',
    slug: 'dataviz-pro',
    tagline: 'Turn your data into beautiful visualizations',
    description:
      'Create interactive charts, graphs, and dashboards from any data source. Perfect for presentations, reports, and data analysis.',
    websiteUrl: 'https://datavizpro.example.com',
    tags: ['Analytics', 'Design', 'SaaS'],
    createdAt: new Date('2024-01-28'),
    approvedAt: new Date('2024-01-29'),
    status: 'approved' as const,
    submittedBy: 'data@example.com',
    voteCount: 234,
  },
  {
    id: 7,
    name: 'EmailCraft',
    slug: 'emailcraft',
    tagline: 'Email marketing made simple and powerful',
    description:
      'Design, send, and track beautiful email campaigns with our intuitive drag-and-drop editor and powerful automation tools.',
    websiteUrl: 'https://emailcraft.example.com',
    tags: ['Marketing', 'Email', 'SaaS'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'email@example.com',
    voteCount: 378,
  },
  {
    id: 8,
    name: 'APIHub',
    slug: 'apihub',
    tagline: 'Manage and monitor all your APIs in one place',
    description:
      'Centralized API management platform with real-time monitoring, documentation, and testing tools. Keep all your APIs organized and secure.',
    websiteUrl: 'https://apihub.example.com',
    tags: ['Developer Tools', 'API', 'Infrastructure'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'api@example.com',
    voteCount: 445,
  },
  {
    id: 9,
    name: 'Developer to Leader Course',
    slug: 'developer-to-leader-course',
    tagline: 'Learn to lead a team of developers',
    description:
      'Learn to lead a team of developers and become a leader in your field. This course is designed for developers who want to take the next step in their career and become a leader in their field.',
    websiteUrl: 'https://developertoleader.com',
    tags: ['Leadership', 'Management', 'Development'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: 'pending' as const,
    submittedBy: 'kulkarni.ankita09@gmail.com',
    voteCount: 340,
  },
  {
    id: 10,
    name: 'AI Content Generator',
    slug: 'ai-content-generator',
    tagline: 'Generate high-quality content with AI in seconds',
    description:
      'Transform your content creation process with AI-powered writing assistant. Generate blog posts, social media content, and marketing copy that engages your audience.',
    websiteUrl: 'https://aicontentgen.example.com',
    tags: ['AI', 'Content', 'Marketing'],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
    approvedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'sarah@example.com',
    voteCount: 789,
  },
  {
    id: 11,
    name: 'SecureVault',
    slug: 'securevault',
    tagline: 'Enterprise-grade password management for teams',
    description:
      "Keep your team's passwords safe with military-grade encryption, secure sharing, and advanced access controls. Perfect for teams of any size.",
    websiteUrl: 'https://securevault.example.com',
    tags: ['Security', 'SaaS', 'Enterprise'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7 days ago
    approvedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'security@example.com',
    voteCount: 456,
  },
  {
    id: 12,
    name: 'DesignKit Pro',
    slug: 'designkit-pro',
    tagline: 'Complete design system for modern web apps',
    description:
      'Accelerate your design workflow with 500+ professionally crafted components, icons, and templates. Built with Tailwind CSS and Figma integration.',
    websiteUrl: 'https://designkit.example.com',
    tags: ['Design', 'UI/UX', 'Tailwind CSS'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000), // 8 days ago
    approvedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'designer@example.com',
    voteCount: 892,
  },
  {
    id: 13,
    name: 'CloudBackup Plus',
    slug: 'cloudbackup-plus',
    tagline: 'Automated backups for your entire infrastructure',
    description:
      'Never lose data again with automated cloud backups, instant recovery, and cross-region replication. Supports all major cloud providers and databases.',
    websiteUrl: 'https://cloudbackup.example.com',
    tags: ['Infrastructure', 'DevOps', 'Cloud'],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000), // 9 days ago
    approvedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'devops@example.com',
    voteCount: 234,
  },
  {
    id: 14,
    name: 'SocialScheduler',
    slug: 'social-scheduler',
    tagline: 'Schedule and manage all your social media posts',
    description:
      'Plan, schedule, and publish content across all major social platforms. Analytics, team collaboration, and AI-powered content suggestions included.',
    websiteUrl: 'https://socialscheduler.example.com',
    tags: ['Social Media', 'Marketing', 'SaaS'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000), // 10 days ago
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'marketing@example.com',
    voteCount: 567,
  },
  {
    id: 15,
    name: 'BugTracker Elite',
    slug: 'bugtracker-elite',
    tagline: 'Track and fix bugs faster with intelligent insights',
    description:
      'Advanced bug tracking with AI-powered duplicate detection, automated triage, and seamless integration with GitHub, Jira, and Slack.',
    websiteUrl: 'https://bugtracker.example.com',
    tags: ['Developer Tools', 'Project Management', 'AI'],
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000), // 11 days ago
    approvedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'dev@example.com',
    voteCount: 423,
  },
  {
    id: 16,
    name: 'FormBuilder Pro',
    slug: 'formbuilder-pro',
    tagline: 'Create powerful forms without writing code',
    description:
      'Build beautiful, responsive forms with drag-and-drop simplicity. Includes conditional logic, payment integration, and advanced analytics.',
    websiteUrl: 'https://formbuilder.example.com',
    tags: ['No-Code', 'Forms', 'SaaS'],
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000), // 12 days ago
    status: 'pending' as const,
    submittedBy: 'forms@example.com',
    voteCount: 312,
  },
  {
    id: 17,
    name: 'SEO Analyzer',
    slug: 'seo-analyzer',
    tagline: 'Comprehensive SEO audits and recommendations',
    description:
      'Improve your search rankings with detailed SEO analysis, competitor insights, and actionable recommendations. Monitor your progress with daily rank tracking.',
    websiteUrl: 'https://seoanalyzer.example.com',
    tags: ['SEO', 'Marketing', 'Analytics'],
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000), // 13 days ago
    status: 'pending' as const,
    submittedBy: 'seo@example.com',
    voteCount: 678,
  },
  {
    id: 18,
    name: 'ChatWidget Live',
    slug: 'chatwidget-live',
    tagline: 'Real-time chat support for your website',
    description:
      'Engage with your visitors instantly using our customizable chat widget. Features include chatbots, canned responses, and multi-language support.',
    websiteUrl: 'https://chatwidget.example.com',
    tags: ['Customer Support', 'SaaS', 'Communication'],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 14 days ago
    status: 'rejected' as const,
    submittedBy: 'support@example.com',
    voteCount: 189,
  },
  {
    id: 19,
    name: 'InvoiceFlow',
    slug: 'invoiceflow',
    tagline: 'Professional invoicing for freelancers and agencies',
    description:
      'Create, send, and track professional invoices in minutes. Automated reminders, payment tracking, and seamless integration with popular payment gateways.',
    websiteUrl: 'https://invoiceflow.example.com',
    tags: ['Finance', 'SaaS', 'Freelance'],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 days ago
    approvedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'invoice@example.com',
    voteCount: 543,
  },
];
